# Generated by Django 4.2.3 on 2023-07-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('documento_ideentidad', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='uploads/fotos')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('certificado_nacimiento', models.ImageField(upload_to='uploads/certificados')),
                ('documento_identidad', models.ImageField(upload_to='uploads/identificacion')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asegurado', to='asegurado.asegurado')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asegurado', to='asegurado.persona')),
            ],
        ),
    ]
