# Generated by Django 4.2.3 on 2023-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asegurado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
