# Generated by Django 4.2.3 on 2023-07-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_alter_contrato_fecha_fin_alter_contrato_fecha_inicio'),
        ('asegurado', '0004_alter_asegurado_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='contratos',
            field=models.ManyToManyField(related_name='asegurados', to='contrato.contrato'),
        ),
    ]
